### ISSUE TITLE
Adjusted close price

### ISSUE THREAD

**Issue by codeterm** [maread99/market_prices#113]
It seems that the output price dataframe does not include the "adj. close" column from Yahoo Finance (or am I missing it somewhere?). As mentiond in the Yahoo Finance footnote:

"Close price adjusted for splits. Adjusted close price adjusted for splits and dividend and/or capital gain distributions."

So the adjusted close is more critical in some, if not most, cases.

**Comment by maread99** [comment]
Hi @codeterm, thanks for raising the issue.

I could probably add an option to the `PricesYahoo` constructor, `adj_close: bool = False`, where setting it to `True` would return the close prices as the 'adj_close'.

Would that work for you?

**Comment by codeterm** [comment]
Hi @maread99, yes, I think that's the perfect way to do it. Thanks!

**Comment by maread99** [comment]
Am I right in thinking this is only relevant when the interval is daily or a multiple of days?

**Comment by codeterm** [comment]
> Am I right in thinking this is only relevant when the interval is daily or a multiple of days?

yes, I think for purely intraday data (within a single day) it is irrelevant.

**Comment by maread99** [comment]
@codeterm, implemented by #118 which has just been merged.

To use the adjusted close prices just pass the new `adj_close` parameter to `PricesYahoo` as `True` (default is `False`).

The functionality will be available if you install from the master (I wasn't planning on publishing a new release to PyPI any time soon).

Any problems, let me know.

Cheers

**Comment by codeterm** [comment]
thanks a lot!
