### ISSUE TITLE
release.yml workflow failing to check new release

### ISSUE THREAD

**Issue by maread99** [maread99/market_prices#22]
Same issue as for [gerrymanoim/exchange_calendars#207](https://github.com/gerrymanoim/exchange_calendars/issues/207) - see notes there.

The 'install and import' check following the upload to the _main_ PyPI repo is NOT installing and importing the uploaded new release, but rather the prior release.

However, the check following the upload to the _test_ PyPI repo does SEEM to be checking the newly uploaded version although, as noted to [exchange_calendars#207](https://github.com/gerrymanoim/exchange_calendars/issues/207), this may not be the case.

**Comment by maread99** [comment]
Changes to the `exchange_calendars` release workflow fixed the bug (gerrymanoim/exchange_calendars/pull/216). However, applying the same changes here has not had the same effect, rather the release workflows for 0.9.2 through 0.9.4 all failed, not because the package release failed (it released fine) but because the subsequent call to pip to install the newly released version could not find it - although the releases could subsequently be installed and imported outside of the workflow.

Annoying.

Wondered if it had anything to do with the `market_prices` release tags being prefixed with the 'v' (unlike `exchange_calendars`). Dropped the 'v' although it didn't seem to make any difference.

**To look into this further**. In the meantime, disabled the install and import check from the 0.9.5 release.

**Until resolved will need to manually check releases install and import successfully.**

- [ ] on resolving, review/revise the [releases doc](https://github.com/maread99/market_prices/blob/master/docs/developers/releases.md)

**Comment by maread99** [comment]
Consider latest comment to https://github.com/gerrymanoim/exchange_calendars/issues/207 and comments [here](https://github.com/rsheftel/pandas_market_calendars/issues/208#issuecomment-1249620294).

**Comment by maread99** [comment]
FINALLY seem to have got there. #95 was the final fix, #96 tidied it up (release 0.9.9).

@Stryder-Git, thought you might be interested in what I've applied from your suggestions and what I couldn't get to work.

Installing the local repo (`pip install -e .`) and renaming came unstuck with `mv: cannot stat 'market_prices': No such file or directory` ([here](https://github.com/maread99/market_prices/actions/runs/3175402708/jobs/5173398618)). I didn't really investigate why, rather I stuck with --no-deps for the PyPI test repo and then installed the dependencies from the main PyPI repo via `pip install -r requirement.txt`.

Your 'while...' line seems to be crucial to getting it working (I added an break to avoid the possibility of an infinite loop). Simply sleeping for 10 seconds just didn't seem to do the job for whatever reason.

Final (hopefully) workflow [here](https://github.com/maread99/market_prices/blob/0.9.9/.github/workflows/release.yml).

Cheers again for your insights on this, not sure I'd have got here otherwise!

**Comment by Stryder-Git** [comment]
@maread99, thanks for the update. It"s strange that mv doesn't work... Adding a break to the loop is a good idea though, thanks!

I'm happy I could help, but I'm happier that we (seem to) have reached the end of the tunnel on this ;) .

**Comment by maread99** [comment]
0.9.10 also released fine and with installation and import checks as required against both the test and main PyPI repos. Closing.
